org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3

# Mod Properties
# The release workflow overrides the version with the one from tools/release_infos.yml.
version=1.5.1
group=eu.explorerseden.nicemerl

# Dependencies
jsoup_version=1.23.2
fabric_permissions_api_version=0.7.0
